config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  # controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
  #   registrations: 'users/registrations' }
  
    get '/auth/facebook/callback', to: 'facebook#auth_done'

    get 'card/new'

    get 'card/show'
  
    get 'cards/new' => 'cards#new'
    get 'cards/show'
  
    resources :card, only: [:new, :show] do
      collection do
        post 'show', to: 'card#show'
        post 'pay', to: 'card#pay'
        post 'delete', to: 'card#delete'
      end
    end

  
   get 'users' => 'users#profile'
   get 'users_identification' => 'users#identification'
   get 'top' => 'top#index'
   get 'users_logout' => 'users#logout'

   def after_sign_out_path_for(resource)
    new_user_session_path
   end

  resources :signup do
    collection do
      get 'step0_1'
      get 'step0_2'
      get 'step1'
      get 'step2'
      get 'step3'
      post 'create'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  root 'items#index'
  resources :users
  resources :items, only: [:index, :show, :new, :edit, :destroy, :create] do

    get  'purchase/:id'=>  'items#purchase', as: 'purchase'
    post 'pay/:id'=>   'items#pay', as: 'pay'#httpメソッドはpostなので注意
    get  'done'=>      'items#done', as: 'done'

    resources :comments, only: [:create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable,omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials, dependent: :destroy
  has_one :card, dependent: :destroy

  # ユーザは複数のコメントが可能　澤木
  has_many :comments

  # ユーザは複数のアイテムを出品している　澤木
  has_many :items


         VALID_EMAIL_REGEX =                 /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

         # step1入力項目
         validates :nickname,                presence: true, length: {maximum: 20}
         validates :email,                   presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
         validates :password,                presence: true, length: {minimum: 6, maximum: 128}
         validates :password_confirmation,   presence: true, length: {minimum: 6, maximum: 128}
         validates :last_name,               presence: true
         validates :first_name,              presence: true
         validates :last_name_kana,          presence: true
         validates :first_name_kana,         presence: true

         validates :birthdate_year,          presence: true
         validates :birthdate_month,         presence: true
         validates :birthdate_day,           presence: true


         validates :phone_number,            presence: true


         # step3入力項目
      
         validates :address_number,          presence: true
         validates :address_prefecture,      presence: true
         validates :address_name,            presence: true
         validates :address_block,           presence: true
        #  validates :address_building,        presence: true
        #  validates :address_phone_number,    presence: true


        #  validates :card_number,             presence: true
        #  validates :expiry_date_month,       presence: true
        #  validates :expiry_date_year,        presence: true
        #  validates :security_code,           presence: true


        







  #  SNSログイン機能。facebookかgoogleからユーザー情報を引っ張り出してreturnする。
  #       このときSNScredentialsテーブルにはuidとproviderを保存するが、User情報は保存しない。
        def self.find_oauth(auth)
          uid = auth.uid
          provider = auth.provider
          snscredential = SnsCredential.where(uid: uid, provider: provider).first
          if snscredential.present? #sns登録のみ完了してるユーザー
            user = User.where(id: snscredential.user_id).first
            unless user.present? #ユーザーが存在しないなら
              user = User.new(
                nickname: auth.info.name,
                email: auth.info.email,
              )
            end
            sns = snscredential
          else #sns登録 未
            user = User.where(email: auth.info.email).first
          if user.present? #会員登録 済
            else #会員登録 未
              user = User.new(
                nickname: auth.info.name,
                email: auth.info.email,
              )
              sns = SnsCredential.new(
                uid: uid,
                provider: provider,
              )
            end
          end
          return {  user: user , sns: sns } # hashでsnsのidを返り値として保持しておく
        end








       



  # has_many :bought_items, foreign_key: "buyer_id", class_name: "Item"
  # has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  # has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"
       
       
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 

  def facebook
    callback_for(:facebook) #コールバック
  end

  def google_oauth2
    callback_for(:google)
  end

  def failure
    redirect_to root_path and return
  end


  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
    @user = info[:user]
    sns_id = info[:sns_id]
    if @user.persisted? #userが存在したら
      sign_in_and_redirect @user, event: :authentication
    else #userが存在しなかったら
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      render template: "signup/step0_1"#redirect_to だと更新してしまうのでrenderで
    end
  end




end
 
 
 
 
 

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  
  def create
    if params[:user][:password] == "" #sns登録なら
      params[:user][:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
      params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
      super
      sns = SnsCredential.update(user_id:  @user.id)
    else #email登録なら
      super
    end
  end
  
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
def new
end

def create
    @foo = Foo.new(foo_params)
    if verify_recaptcha(model: @foo, env: Rails.env) && @foo.save
      redirect_to @foo
    else
      render 'new'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
  @nickname = current_user.nickname
  @items = Item.where(seller_id: current_user.id)
 end

 def edit
 end

 def identification
  @last_name = current_user.last_name
  @first_name = current_user.first_name
 end

 def new
    @user = current_user.id
    @user.create(user_params)
   else
 end

 def profile
  @nickname = current_user.nickname
 end
 def logout
 end

 private

 def user_params
 params.permit(:address_number,:address_prefecture,:address_name,:address_block,:address_building)
 end
end

app/views/users/_side-list.html.haml
%nav.side
  %ul
    %li.list
      =link_to "#",class:"list__item" do
        マイページ
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        お知らせ 
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        やることリスト
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        いいね！一覧
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        出品する
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item exhibiting" do
        出品した商品-出品中
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        出品した商品-取引中
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        出品した商品-売却済み
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        購入した商品-取引中
        %i.fa.fa-chevron-right
    %li.list 
      =link_to "#",class:"list__item" do
        購入した商品-過去の取引
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        ニュース一覧
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        評価一覧
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        ガイド
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        お問い合わせ
        %i.fa.fa-chevron-right
    %h3.list__item2 メルペイ
    %li.list
      =link_to "#",class:"list__item" do
        売上・振込申請
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        ポイント
        %i.fa.fa-chevron-right
    %h3.list__item2 設定
    %li.list
      =link_to users_path(current_user),class:"list__item" do
        プロフィール
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        発送元・お届け先住所変更
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        支払い方法
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        メール/パスワード
        %i.fa.fa-chevron-right
    %li.list
      =link_to users_identification_path(current_user), class:"list__item" do
        本人情報
        %i.fa.fa-chevron-right
    %li.list
      =link_to "#",class:"list__item" do
        電話番号の確認
        %i.fa.fa-chevron-right
    %li.list
      =link_to users_logout_path(current_user),class:"list__item" do
        ログアウト
        %i.fa.fa-chevron-right

app/views/users/identification.html.haml
= render 'layouts/header'

.container
  .container--wrapper
    .container--side
      = render "side-list"
    .l-contents
      %section.l-chapter-container.mypage-identification
        %h2.l-chapter-top 本人情報の登録
        %form.l-inner{:action => "#", :method => "POST"}
          %div
            %p.l-inner-text
              お客さまの本人情報をご登録ください。
              %br>/
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p.text-right
              %a{:href => "#", :target => "_blank"}
                本人確認書類のアップロードについて
                %i.icon-arrow-right
          .form-group
            %label お名前
            %p
              = current_user.last_name
              = current_user.first_name
          .form-group
            %label お名前カナ
            %p
              = current_user.last_name_kana
              = current_user.first_name_kana

          .form-group
            %label{:for => "birthday"} 生年月日
            %p 
              = current_user.birthdate_year
              \/
              = current_user.birthdate_month
              \/
              = current_user.birthdate_day
          .form-group
            %label{:for => "zip_code"} 郵便番号
            %span.form-arbitrary 任意
            %input.input-standard{:name => "zip_code", :placeholder => "例）1234567", :type => "text", :value => ""}/
          .form-group
            %label{:for => "prefecture"} 都道府県
            %span.form-arbitrary 任意
            .select-box
              %i.icon-arrow-bottom
              %select.select-default{:name => "prefecture"}
                %option --
                %option 北海道
                %option 青森県
                %option 岩手県
                %option 宮城県
                %option 秋田県
                %option 山形県
                %option 福島県
                %option 東京都
                %option 神奈川県
                %option 埼玉県
                %option 千葉県
                %option 茨城県
                %option 栃木県
                %option 群馬県
                %option 山梨県
                %option 新潟県
                %option 長野県
                %option 富山県
                %option 石川県
                %option 福井県
                %option 愛知県
                %option 岐阜県
                %option 静岡県
                %option 三重県
                %option 大阪府
                %option 兵庫県
                %option 京都府
                %option 滋賀県
                %option 奈良県
                %option 和歌山県
                %option 鳥取県
                %option 島根県
                %option 岡山県
                %option 広島県
                %option 山口県
                %option 徳島県
                %option 香川県
                %option 愛媛県
                %option 高知県
                %option 福岡県
                %option 佐賀県
                %option 長崎県
                %option 熊本県
                %option 大分県
                %option 宮崎県
                %option 鹿児島県
                %option 沖縄県
          .form-group
            %label{:for => "city"} 市区町村
            %span.form-arbitrary 任意
            %input.input-standard{:name => "city", :placeholder => "例) 横浜市緑区", :type => "text", :value => ""}/
          .form-group
            %label{:for => "address1_label"} 番地
            %span.form-arbitrary 任意
            %input.input-standard{:name => "address1", :placeholder => "例) 青山1−1−1", :type => "text", :value => ""}/
          .form-group
            %label{:for => "address2_label"} 建物名
            %span.form-arbitrary 任意
            %input.input-standard{:name => "address2", :placeholder => "例) 柳ビル103", :type => "text", :value => ""}/
          %button.btn-red{:type => "submit"} 登録する
          .form-group.text-right
            %p
              %a{:href => "#", :target => "_blank"}
                本人情報の登録について
                %i.icon-arrow-right
          %input{:name => "__csrf_value", :type => "hidden", :value => "d617bb392c01934c0028e66423c2e70d63bd8fed843040cfebf3695554e1c0058d43e4a4de3f494a5720994c9e8324f9908b9f5b32f69a9b946e46776fe59dd29"}/

= render 'layouts/footer'

app/views/users/logout.html.haml
= render 'layouts/header'

.container
  .container--wrapper
    .container--side
      = render "side-list"
    .user-content
      .user-chapter-container
        .user-mypage-logout-inner
          .mypage-logout-content
            = link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "btn-default btn-red text-default__submit"
            .emptybox-mypage-logout




= render 'layouts/footer'

app/views/users/profile.html.haml
= render 'layouts/header'

.container
  .container--wrapper
    .container--side
      = render "side-list"

    .main__profile
      .main__profile__top
        %pプロフィール
      .main__profile__middle1
        .main--icon
          =image_tag "user-bg.jpg",class: "main-icon__back1"
          =link_to "#",class: "main--icon__icon" do
            %figure.main--icon__figure
              =image_tag("member_photo_noimage.png",width: "60",height: "60", alt: "サンプル画像",class:"main--icon__back2")
              %input.input__nickname{placeholder: "#{current_user.nickname}"}
      .main__profile__middle2
        %textarea{:placeholder => "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
      .main__profile__bottom
        = link_to "変更する",  "#", method: :delete, class: "btn-default btn-red text-default__submit"


= render 'layouts/footer'

app/views/users/show.html.haml
= render 'layouts/header'

.container
  .container--wrapper
    .container--side
      = render "side-list"
    .main
      .main--icon
        =image_tag "user-bg.jpg",class: "main-icon__back1"
        =link_to "#",class: "main--icon__icon" do
          %figure.main--icon__figure
            =image_tag("member_photo_noimage.png",width: "60",height: "60", alt: "サンプル画像",class:"main--icon__back2")
            %h2.main--icon__figure__user
              = current_user.nickname
            %div
              %div.main--icon__figure__user__rate
                評価 0
              %div.main--icon__figure__user__rate
                出品数 0
      .main--inform 
        %ul.main--inform__tab0
          %li.main--inform__tab1
            =link_to "#",class:"main--inform__tab1__a" do
              お知らせ
          %li.main--inform__tab1
            =link_to "#",class:"main--inform__tab1__a" do
              やることリスト
        .main--contents
          %div
            %ul.main--contents
              %li.main--contents--tab3
                =link_to "#",class:"main--contents--tab3--link" do
                  %figure.main--contents--tab3--link__figure
                    =image_tag("mercari_profile.png",width:"48",height:"48", alt:"メルカリ",class:"main--contents__icon")
                  %div.main--contents--tab3--link__text
                    %div
                      《ご登録記念》¥1,000の商品を実質「実質１円」で購入いただけます！
                    %time
                      %i.icon-time
                        7時間前
                  %i.fa.fa-chevron-right
              %li.main--contents--tab3
                =link_to "#",class:"main--contents--tab3--link" do
                  %figure.main--contents--tab3--link__figure
                    =image_tag("mercari_profile.png",width:"48",height:"48", alt:"メルカリ",class:"main--contents__icon")
                  %div.main--contents--tab3--link__text
                    %div
                      《ご登録記念》¥1,000の商品を実質「実質１円」で購入いただけます！
                    %time
                      %i.icon-time
                        7時間前
                  %i.fa.fa-chevron-right
              %li.main--contents--tab3
                =link_to "#",class:"main--contents--tab3--link" do
                  %figure.main--contents--tab3--link__figure
                    =image_tag("mercari_profile.png",width:"48",height:"48", alt:"メルカリ",class:"main--contents__icon")
                  %div.main--contents--tab3--link__text
                    %div
                      《ご登録記念》¥1,000の商品を実質「実質１円」で購入いただけます！
                    %time
                      %i.icon-time
                        7時間前
                  %i.fa.fa-chevron-right
              %li.main--contents--tab3
                =link_to "#",class:"main--contents--tab3__gray"do
                  一覧をみる
              
      .main--history
        %h2.main--history__top 購入した商品
        %ul
          %li.main--history__tab3
            %h3 取引中
          %li.main--history__tab3
            %h3 過去の取引
        %div.main--history__bottom

    .product-list
      .product-list__contents
        %div
          %ul.product-list__contents
          - @items.each do |item|
            %li.product-list__contents--tab3
              =link_to "#",class:"product-list__contents--tab3--link" do
                %figure.product-list__contents--tab3--link__figure
                  = image_tag( item.image, width:"48",height:"48", alt:"メルカリ",class:"main--contents__icon")
                %div.product-list__contents--tab3--link__text
                  %div
                    = item.name
                  %time
                    %i.icon-time
                      = time_ago_in_words(item.created_at)
                      前
                %i.fa.fa-chevron-right
= render 'layouts/footer'