config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  # controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
  #   registrations: 'users/registrations' }
  
    get '/auth/facebook/callback', to: 'facebook#auth_done'

    get 'card/new'

    get 'card/show'
  
    get 'cards/new' => 'cards#new'
    get 'cards/show'
  
    resources :card, only: [:new, :show] do
      collection do
        post 'show', to: 'card#show'
        post 'pay', to: 'card#pay'
        post 'delete', to: 'card#delete'
      end
    end

  
   get 'users' => 'users#profile'
   get 'users_identification' => 'users#identification'
   get 'top' => 'top#index'
   get 'users_logout' => 'users#logout'

   def after_sign_out_path_for(resource)
    new_user_session_path
   end

  resources :signup do
    collection do
      get 'step0_1'
      get 'step0_2'
      get 'step1'
      get 'step2'
      get 'step3'
      post 'create'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  root 'items#index'
  resources :users
  resources :items, only: [:index, :show, :new, :edit, :destroy, :create] do

    get  'purchase/:id'=>  'items#purchase', as: 'purchase'
    post 'pay/:id'=>   'items#pay', as: 'pay'#httpメソッドはpostなので注意
    get  'done'=>      'items#done', as: 'done'

    resources :comments, only: [:create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
 
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller, optional: true, class_name: "User"
  belongs_to :buyer, optional: true, class_name: "User"
  # belongs_to :user
  has_many :comments

  # belongs_to :details_category_major

  has_many :images, dependent: :destroy


  mount_uploader :image, ImageUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :pay, :purchase]

  def index
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to root_path
    
    # if @item.save
    #   redirect_to root_path, notice: '商品を登録しました'
    # else
    #   # render :new
    # end

  end

  def new
    if user_signed_in?
      @item = Item.new
      @category_parents = Category.all.where(ancestry: nil)
    else
      redirect_to new_user_session_path
    end

    # gon.item = @item
    # gon.images = @item.images

    # # @item.item_imagse.image_urlをバイナリーデータにしてビューで表示できるようにする
    # require 'base64'
    # # require 'aws-sdk'

    # gon.images_binary_datas = []
    # if Rails.env.production?
    #   client = Aws::S3::Client.new(
    #                          region: 'ap-northeast-1',
    #                          access_key_id: Rails.application.credentials.aws[:access_key_id],
    #                          secret_access_key: Rails.application.credentials.aws[:secret_access_key],
    #                          )
    #   @item.images.each do |image|
    #     binary_data = client.get_object(bucket: 'freemarket-sample-51a', key: image.image_url.file.path).body.read
    #     gon.images_binary_datas << Base64.strict_encode64(binary_data)
    #   end
    # else
    #   @item.images.each do |image|
    #     binary_data = File.read(image.image_url.file.file)
    #     gon.images_binary_datas << Base64.strict_encode64(binary_data)
    #   end
    # end
  end

  def edit
  end

  def show
    @comments = @item.comments.includes(:user)
    @user = User.find(@item.seller_id)
  end

  def update
  end

  def destroy
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
#選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  # def search
  #   respond_to do |format|
  #     format.html
  #     format.json do
  #      @children = Category.find(params[:parent_id]).children
  #     end
  #   end
  # end

  def purchase
    if user_signed_in?
      
      card = current_user.card
      #テーブルからpayjpの顧客IDを検索
      @user = User.find(@item.seller_id)
      unless @item.seller_id == @item.buyer_id
        redirect_to root_path
      else
      end
  
      if card.blank?
        #登録された情報がない場合にカード登録画面に移動
        redirect_to controller: "card", action: "new"
      else
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        #保管した顧客IDでpayjpから情報取得
        customer = Payjp::Customer.retrieve(card["customer_id"])
        #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
        @default_card_information = customer.cards.retrieve(card.card_id)
        @card_brand = @default_card_information.brand
        @card_src = "Visa.png"
      end

    else
      redirect_to new_user_session_path
    end

  end

  def pay
    card = current_user.card
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    amount: @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    customer: card.customer_id, #顧客ID
    currency: 'jpy' #日本円
    )
    @item.update(buyer_id: current_user.id)
    redirect_to action: 'done'
  end

  def done
  end

  private

  def item_params
    params.require(:item).permit(:image,
                                 :name,
                                 :explanation,
                                 :details_size,
                                 :details_state,
                                 :delivery_fee,
                                 :delivery_area,
                                 :delivery_days,
                                 :price)
                                 .merge(seller_id: 1)
                                 .merge(buyer_id: 1)
                                 .merge(details_category_major: "ダミー")
                                 .merge(details_category_medium: "ダミー")
                                 .merge(details_category_minor: "ダミー")
  end

  def set_item
    @item = Item.find(params[:id])
  end

  # def registered_image_params
  #   params.require(:registered_images_ids).permit({ids: []})
  # end

  # def new_image_params
  #   params.require(:new_images).permit({images: []})
  # end


end

app/views/items/done.html.haml
= render 'layouts/header'

%body
  %main.itemDetails-main
    .itemDetails-container
      .itemDetails-container__header
        .item__details__box__top
          %p完了しました
          = link_to "トップページへ",  root_path, method: :get,class: "toppage__box__change"


= render 'layouts/footer'

app/views/items/edit.html.haml
= render 'layouts/header'

.container
  .container--wrapper
    .container--side
      = render "layouts/side-list"
    .main-edit
      .itemDetails-container
      .itemDetails-container__header
        %p 
          = @item.name
        -# mulinsen　(　ムーリンセン　) 本革 レース　アップ　シューズ 日本製
      .itemDetails-container__main
        .itemDetails-container__main__left
          .itemDetails-container__main__left__image
            -# %img{:alt => "", :src => "img/sample.jpg"}/
            = image_tag @item.image
        .itemDetails-container__main__right
          .itemDetails-container__main__right__table
            %table
              %tr.exhibitor
                %th 出品者
                %td 
                  = @user.nickname
              %tr.category
                %th カテゴリー
                %td 
                  = @item.details_category_major
                  = @item.details_category_medium
                  = @item.details_category_minor
              %tr
                %th ブランド
                %td シャネル
              %tr
                %th 商品のサイズ
                %td
                  = @item.details_size
              %tr
                %th 商品の状態
                %td
                  = @item.details_state
              %tr
                %th 配送料の負担
                %td
                  = @item.delivery_fee
              %tr
                %th 配送の方法
                %td らくらくメルカリ便
              %tr
                %th 配送元地域
                %td
                  = @item.delivery_area
              %tr
                %th 発送日の目安
                %td
                  = @item.delivery_days
        .itemDetails-container__main__price
          %p.itemDetails-container__main__price--mark¥
          %p.itemDetails-container__main__price--price
            = @item.price
          %p.itemDetails-container__main__price--tax (税込)
          %p.itemDetails-container__main__price--postage 送料込み
        .itemDetails-container__main__btn
          = link_to "商品の編集", "/users/#{@user.id}/items/#{@item.id}/rewrite"
        .itemDetails-container__main__btn--delete
          %a{:href => ""} この商品を削除する
= render 'layouts/footer'

app/views/items/index.html.haml
= render 'layouts/header'
= render 'layouts/advertisement'
.funcBtn
  = link_to "出 品", "/items/new", class: "funcBtn"
.main-container
  .popular
    %h2.popular__title 人気のカテゴリー
    .popular__body
      %ul.popular__body__list
        %li.popular__body__list__item
          = link_to "レディース", "#ladies", class: "popular__body__list__btn"
        %li.popular__body__list__item
          = link_to "メンズ", "#mens", class: "popular__body__list__btn"
        %li.popular__body__list__item
          = link_to "家電・スマホ・カメラ", "#appliance", class: "popular__body__list__btn"
        %li.popular__body__list__item
          = link_to "おもちゃ・ホビー・グッズ", "#toys", class: "popular__body__list__btn"
  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "ladies" } レディース新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"


              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name

                -unless item.buyer_id == 1 
                  .items-box_photo__sold
                    .items-box_photo__sold__inner
                      SOLD


  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "mens" }  メンズ新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"
              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name
  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "appliance" }  家電・スマホ・カメラ新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"
              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name
  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "toys" }  おもちゃ・ホビー・グッズ新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"
              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name
  .popular
    %h2.popular__title 人気のブランド
    .popular__body
      %ul.popular__body__list
        %li.popular__body__list__item
          = link_to "シャネル", "#chanel", class: "popular__body__list__btn"
        %li.popular__body__list__item
          = link_to "ルイヴィトン", "#louisvuitton", class: "popular__body__list__btn"
        %li.popular__body__list__item
          = link_to "シュプリーム", "#supreme", class: "popular__body__list__btn"
        %li.popular__body__list__item
          = link_to "ナイキ", "#nike", class: "popular__body__list__btn"
  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "chanel" } シャネル新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"
              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name
  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "louisvuitton" } ルイヴィトン新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"
              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name
  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "supreme" } シュプリーム新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"
              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name
  .newcomers
    .newcomers__group
      .newcomers__group__header{name: "scroll-1"}
        %h3{ id: "nike" } ナイキ新着アイテム
        = link_to "もっと見る ＞", "/jp/category/1/", class: "newcomers__group__header__more"
      .newcomers__group__list
        - @items.each do |item|
          = link_to item_path(item.id) do
            .newcomers__group__list__item
              = image_tag item.image, class: "newcomers__group__list__item__image"
              .newcomers__group__list__item__price
                = item.price
              .newcomers__group__list__item__name
                .newcomers__group__list__item__name__text
                  = item.name
= render 'layouts/footer'

app/views/items/new.html.haml
%body
  .single-container
    %header.single-header
      %a{href: "/"}
        %h1
          = image_tag 'logo.svg', alt: "mercari", class: 'signup-header__img'
          
    %main.single-main
      %section.sell-container
        %h2.l-single-head 商品の情報を入力
        = form_for @item do |f|
          .sell-upload-box
            = f.file_field :image, class: "sell-upload-drop-file"
            %h3.sell-upload-head
              出品画像
              %span.form-require 必須
            %p 最大10枚までアップロードできます

          .sell-content
            .form-group
              %label
                商品名
                %span.form-require 必須
              %div
                = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "input-default"
            .form-group
              %label
                商品の説明
                %span.form-require 必須
              = f.text_area :explanation, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "textarea-default", size: "200x5"
          .sell-content.clearfix
            %h3.sell-sub-head 商品の詳細
            .sell-form-box
              .listing-product-detail__category
                %label
                  カテゴリー
                %span.form-require 必須
                .category-select-wrap
                  .select-wrap__box#parent_wrapper
                    = f.collection_select :details_category_major, @category_parents, :id, :name, {prompt: "---"}, class: "select-default", id: "parent_category"
                    %i.fas.fa-chevron-down.listing-select-wrapper__box--arrow-down
              .form-group
                %label
                  商品のサイズ
                  %span.form-require 必須
                .select-wrap
                  %i.icon-arrow-bottom
                  = f.select :details_size, ["---", "新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり","傷や汚れあり", "全体的に状態が悪い"], {}, class: "select-default"
                %label
                  商品の状態
                  %span.form-require 必須
                .select-wrap
                  %i.icon-arrow-bottom
                  = f.select :details_state, ["---", "新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり","傷や汚れあり", "全体的に状態が悪い"], {}, class: "select-default"
          .sell-content.clearfix
            %h3.sell-sub-head 配送について
            %a.form-question{:href => "/jp/help_center/article/68/", :target => "_blank"} ?
            .sell-form-box
              .form-group
                %label
                  配送料の負担
                  %span.form-require 必須
                .select-wrap
                  %i.icon-arrow-bottom
                  = f.select :delivery_fee, ["---", "送料込み(出品者負担)", "着払い(購入者負担)"], {}, class: "select-default"
              .form-group
                %label
                  発送元の地域
                  %span.form-require 必須
                .select-wrap
                  %i.icon-arrow-bottom
                  = f.select :delivery_area, ["---",   |
                    "北海道",                             |
                    "青森県",                             |
                    "岩手県",                             |
                    "宮城県",                             |
                    "秋田県",                             |
                    "山形県",                             |
                    "福島県",                             |
                    "茨城県",                             |
                    "栃木県",                             |
                    "群馬県",                             |
                    "埼玉県",                             |
                    "千葉県",                             |
                    "東京都",                             |
                    "神奈川県",                            |
                    "新潟県",                             |
                    "富山県",                             |
                    "石川県",                             |
                    "福井県",                             |
                    "山梨県",                             |
                    "長野県",                             |
                    "岐阜県",                             |
                    "静岡県",                             |
                    "愛知県",                             |
                    "三重県",                             |
                    "滋賀県",                             |
                    "京都府",                             |
                    "大阪府",                             |
                    "兵庫県",                             |
                    "奈良県",                             |
                    "和歌山県",                            |
                    "鳥取県",                             |
                    "島根県",                             |
                    "岡山県",                             |
                    "広島県",                             |
                    "山口県",                             |
                    "徳島県",                             |
                    "香川県",                             |
                    "愛媛県",                             |
                    "高知県",                             |
                    "福岡県",                             |
                    "佐賀県",                             |
                    "長崎県",                             |
                    "熊本県",                             |
                    "大分県",                             |
                    "宮崎県",                             |
                    "鹿児島県",                            |
                    "沖縄県",                             |
                    "未定"], {}, class: "select-default" |
              .form-group
                %label
                  発送までの日数
                  %span.form-require 必須
                .select-wrap
                  %i.icon-arrow-bottom
                  = f.select :delivery_days, ["---", "1~2日で発送", "2~3日で発送", "4~7日で発送"], {}, class: "select-default"
          .sell-content.clearfix
            %h3.sell-sub-head 販売価格(300〜9,999,999)
            %a.form-question{:href => "/jp/help_center/article/64/", :target => "_blank"} ?
            .sell-form-box
              %ul.sell-price
                %li.form-group
                  .clearfix
                    %label.l-left
                      価格
                      %span.form-require 必須
                    .l-right_3
                      .sell-price-input
                        %div
                          = f.text_field :price, placeholder: "例）300", class: "input-default", id: 'profit_calc', autocomplete: 'off'
                %li.clearfix
                  .l-left
                    販売手数料 (10%)
                  .l-right
                %li.clearfix.bold
                  .l-left
                    販売利益
                  .l-right_2
                    = f.number_field :price, style: "display: none", id: "price"
          .sell-content.sell-btn-box
            %div
              %p 禁止されている出品、行為を必ずご確認ください。
              %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
              %p また、出品をもちまして加盟店規約に同意したことになります。
            = f.submit "出品する", class: "sell-btn__red"
            %a.sell-btn__gray もどる
    %footer.single-footer
      %nav
        %ul.clearfix
          %li プライバシーポリシー
          %li メルカリ利用規約
          %li 特定商取引に関する表記
      %a.single-footer-logo{href: "/"}
        = image_tag 'logo-gray.svg', alt: 'mercari'
      %p
        %small © 2019 Mercari

app/views/items/purchase.html.haml
= render 'layouts/header'



%body
  %main.itemDetails-main
    .itemDetails-container
      .itemDetails-container__header
        .item__details__box__top
          %p購入内容の確認 


        .item__details__box__middle1
          %form.buy-form
            %p
              = image_tag @item.image
            %p
              = @item.name
            %p
              = "¥#{@item.price} 送料込み ポイントはありません"
            

            %p
              支払い金額
              = "¥#{@item.price}"
            %p
              = link_to "購入する", item_pay_path(@item.id), method: :post, class: "itemDetails-container__purchase__btn"
          

        .item__details__box__middle2
          .card__information
            支払い方法：クレジットカード
          .card__information__number
            = "**** **** **** #{@default_card_information.last4}"
          .card__information__exp
            = "有効期限：#{@default_card_information.exp_month.to_s}/#{@default_card_information.exp_year.to_s.slice(2,3)}"
          = image_tag "#{@card_src}", width: '40', height: '20', alt: @card_brand, id: "card_image"
          =link_to "#", class: "card__box__change" do  
            変更する

        .item__details__box__middle3
          .user__address
            配送先
          .user__address__number
            = "〒#{current_user.address_number}"
          .user__address__information
            = current_user.address_prefecture
            = current_user.address_name
            = current_user.address_block
            = current_user.address_building
          =link_to "#", class: "card__box__change" do  
            変更する

= render 'layouts/footer'

app/views/items/show.html.haml
= render 'layouts/header'
%body
  %main.itemDetails-main
    .itemDetails-container
      .itemDetails-container__header
        %p 
          = @item.name
        -# mulinsen　(　ムーリンセン　) 本革 レース　アップ　シューズ 日本製
      .itemDetails-container__main
        .itemDetails-container__main__left
          .itemDetails-container__main__left__image
            -# %img{:alt => "", :src => "img/sample.jpg"}/
            = image_tag @item.image
        .itemDetails-container__main__right
          .itemDetails-container__main__right__table
            %table
              %tr.exhibitor
                %th 出品者
                %td 
                  = @user.nickname
              %tr.category
                %th カテゴリー
                %td 
                  = @item.details_category_major
                  = @item.details_category_medium
                  = @item.details_category_minor
              %tr
                %th ブランド
                %td シャネル
              %tr
                %th 商品のサイズ
                %td
                  = @item.details_size
              %tr
                %th 商品の状態
                %td
                  = @item.details_state
              %tr
                %th 配送料の負担
                %td
                  = @item.delivery_fee
              %tr
                %th 配送の方法
                %td らくらくメルカリ便
              %tr
                %th 配送元地域
                %td
                  = @item.delivery_area
              %tr
                %th 発送日の目安
                %td
                  = @item.delivery_days
        .itemDetails-container__main__price
          %p.itemDetails-container__main__price--mark¥
          %p.itemDetails-container__main__price--price
            = @item.price
          %p.itemDetails-container__main__price--tax (税込)
          %p.itemDetails-container__main__price--postage 送料込み
        .itemDetails-container__main__btn
          = link_to "購入画面に進む",  item_purchase_path(@item.id), method: :get
        .itemDetails-container__main__explanation
          %p
            = @item.explanation
        .itemDetails-container__main__bottom
          .itemDetails-container__main__bottom--good
            %a{:href => ""} いいね
          .itemDetails-container__main__bottom--report
            %a{:href => ""} 不適切な商品の報告
          .itemDetails-container__main__bottom--effort
            %a{:href => ""} あんしん・あんぜんへの取り組み
    .itemDetails-comment-container
      - if @comments
        - @comments.each do |comment|
          .itemDetails-comment-container__comments
            -# %img{:alt => "", :src => "img/user-icon.svg"}/
            = image_tag 'user-icon.svg'
            .chatting
              = comment.user.nickname
              .says
                %p
                  = comment.text
                %p.time-ago
                  = time_ago_in_words(comment.created_at)
                  前
      .itemDetails-comment-container__rule
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .itemDetails-comment-container__textarea
        = form_tag("/items/#{@item.id}/comments", method: :post) do
          = text_area_tag :text
          .itemDetails-comment-container__btn
            = submit_tag "コメントする"
= render 'layouts/footer'