config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  # controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
  #   registrations: 'users/registrations' }
  
    get '/auth/facebook/callback', to: 'facebook#auth_done'

    get 'card/new'

    get 'card/show'
  
    get 'cards/new' => 'cards#new'
    get 'cards/show'
  
    resources :card, only: [:new, :show] do
      collection do
        post 'show', to: 'card#show'
        post 'pay', to: 'card#pay'
        post 'delete', to: 'card#delete'
      end
    end

  
   get 'users' => 'users#profile'
   get 'users_identification' => 'users#identification'
   get 'top' => 'top#index'
   get 'users_logout' => 'users#logout'

   def after_sign_out_path_for(resource)
    new_user_session_path
   end

  resources :signup do
    collection do
      get 'step0_1'
      get 'step0_2'
      get 'step1'
      get 'step2'
      get 'step3'
      post 'create'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  root 'items#index'
  resources :users
  resources :items, only: [:index, :show, :new, :edit, :destroy, :create] do

    get  'purchase/:id'=>  'items#purchase', as: 'purchase'
    post 'pay/:id'=>   'items#pay', as: 'pay'#httpメソッドはpostなので注意
    get  'done'=>      'items#done', as: 'done'

    resources :comments, only: [:create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
 
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"
  
  def new
    card = Card.where(user_id: current_user.id)
  end

  
  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    binding.pry
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else

      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      card: params['payjp-token']
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to done_signup_index_path
    else
        redirect_to action: "pay"
      end
    end
  end
  
  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end
  
  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
  end
 end
end

app/views/card/new.html.haml
-# = form_for @user, url: signup_index_path, method: :post, action: "create", html: {class: 'forth-main-wrapper__box'} do |f|
-#   = f.text_field :card_number, required:"required"
-#   = f.text_field :expiry_date_month, required:"required"
-#   = f.text_field :expiry_date_year, required:"required"
-#   = f.text_field :security_code, required:"required"
-#   = f.submit '次へ進む', class: 'register-profile__nextpage'
%body
  %header.registCard-header
    .registCard-header__container
      %a.registCard-header__link{:href => ""}
        = image_tag 'logo.svg', class: 'regist-header__img'
      .steplist-container
        %ul.steplist-container__steplist
          %li.completed
            %span.bubble
            %p 会員情報
          %li.completed
            %span.bubble
            %p 電話番号認証
          %li.completed
            %span.bubble
            %p お届け先住所入力
          %li.entering
            %span.bubble
            %p 支払い方法
          %li
            %span.bubble
            %p 完了
  %main.registCard-main
    .registCard-container
      .registCard-container__header
        %p 支払い方法
      .registCard-container__form
        = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do       
          .registCard-container__form--text
            %p カード番号
            %p.registCard-container__form__required 必須
            -# %input{:placeholder => "　半角数字のみ", :type => "number"}/
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          = image_tag 'card.png', class: 'registCard-container__form__cardList'
          .registCard-container__form--text
            %p 有効期限
            %p.registCard-container__form__required 必須
            .registCard-container__form--deadline
              -# %select#exp_month{name: "exp_month", type: "text", class: "month registCard-container__form__month", required:"required"},[["01", 1,],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]]
              -# = select :exp_month, [["01", 1,],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]], class: "month registCard-container__form__month", name: "exp_month", type: "text", required:"required"
              -# 月
              %select#exp_month{name: "exp_month", type: "text", class: "month registCard-container__form__month", required:"required"}
                %option{:value => ""} --
                %option{:value => "1"} 01
                %option{:value => "2"} 02
                %option{:value => "3"} 03
                %option{:value => "4"} 04
                %option{:value => "5"} 05
                %option{:value => "6"} 06
                %option{:value => "7"} 07
                %option{:value => "8"} 08
                %option{:value => "9"} 09
                %option{:value => "10"} 10
                %option{:value => "11"} 11
                %option{:value => "12"} 12
              %span 月/
              -# = select :exp_year, [["19", 2019,],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029],["30",2030]], class: "year", name: "exp_year", type: "text", required:"required"
              -# 年
              -# = succeed "\u{3000}\u{5e74}" do
              -# %select#exp_year{name: "exp_year", type: "text", class: "year", required:"required}
              %select#exp_year{name: "exp_year", type: "text", class: "year"}
                %option{:value => ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年/
            .registCard-container__form--text
              %p セキュリティコード
              %p.registCard-container__form__required 必須
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              -# %input{:placeholder => "　カード背面4桁もしくは3桁の番号", :type => "number"}/
            %a.registCard-container__form__about{:href => ""} カード背面の番号とは？
            .registAdress-container__form--submit
              = submit_tag '次へ進む',  id: "token_submit", class: 'register-profile__nextpage'
              -# %input{:type => "submit", :value => "次へ進む"}/
      %footer.registCard-footer
        .registCard-footer__rule
          %a{:href => ""} プライバシーポリシー
          %a{:href => ""} メルカリ利用規約
          %a{:href => ""} 特定商取引に関する表記
        .registCard-footer__logo
          %a{:href => ""}
            = image_tag 'logo-gray.svg'
        .registCard-footer__copyRight
          %p © 2019 TeamA

app/views/card/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(card_delete_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する 